### PR TITLE
Added iStat Menus 5 support

### PR DESCRIPTION
**Pull request by jverdeyen**

### CODE REVIEW

**Comment by swrobel** [comment]
This working for everyone else? iStat Menus 5.11 seems to keep overwriting `Library/Preferences/com.bjango.istatmenus5.extras.plist` with a non-symlinked default version

**Comment by jverdeyen** [comment]
Feels like I'm having the same issue with 5.11.

**Comment by lra** [comment]
If this is broken, a PR to remove support is welcome

**Comment by guillaumealgis** [comment]
Same here, reproduced the problem reliably multiple times with iStatMenus 5.20 (682).
I contacted bjango to let them know of the issue. If they don't respond or don't address the issue, I'll submit a PR removing the app :'(

**Comment by guillaumealgis** [comment]
Well, they did not respond to my ticket but they fixed it anyway, the symlink is no longer overwritten anymore on 5.2 🎉

**Pull request merged**
