### PR TITLE
add support for Elgato StreamDeck (close #1667)

### LINKED ISSUE #1667: Add Elgato Stream Deck
It would nice if mackup backup the [Elgato Stream Deck app](https://www.elgato.com/en/gaming/downloads)

### PR DESCRIPTION
**Pull request by fharper**
### All submissions

* [ X ] I have followed the [Contributing Guidelines](https://github.com/lra/mackup/blob/master/.github/CONTRIBUTING.md)
* [ X] I have checked to ensure there aren't other open [Pull Requests](https://github.com/lra/mackup/pulls) for the same update/change

### Adding/updating Application X Support

* [ X] This PR is only for one application
* [X ] It has been added to the list of supported applications in the [README](https://github.com/lra/mackup/blob/master/README.md)
* [X ] Changes have been added to the WIP section of the [CHANGELOG](https://github.com/lra/mackup/blob/master/CHANGELOG.md)
* [ X] Syncing does not break the application
* [X ] Syncing does not compete with any syncing functionality internal to the application
* [X ] The configuration syncs the minimal set of data
* [ X] No file specific to the local workstation is synced
* [X ] No sensitive data is synced

### Improving the Mackup codebase

* [ ] My submission passes the [tests](https://github.com/lra/mackup/tree/master/tests)
* [ ] I have linted the code locally prior to submission
* [ ] I have written new tests as applicable
* [ ] I have added an explanation of what the changes do

### CODE REVIEW

**Comment by joshmedeski** [comment]
I've got a streamdeck, thanks!

Please make sure to run your file changes with the Black formatter.

**Comment by fharper** [comment]
@joshmedeski: what do you want me to lint, I changed no Python files.

**Comment by joshmedeski** [comment]
@lra, looks like there may be an issue with "Lint Python / black" in CI on this PR.

**Comment by fharper** [comment]
@joshmedeski: so it can be merged since there is no issue with Python code in this PR no?

**Comment by joshmedeski** [comment]
I guess so, but @lra is the who who can merge.

**Comment by lra** [comment]
It's on my, black released a new version, I'll fix it 1st: https://github.com/lra/mackup/pull/1912

**Pull request merged**
