### PR TITLE
Added support for Xcode plugins.

### PR DESCRIPTION
**Pull request by bartoszj**

### CODE REVIEW

**Comment by lra** [comment]
https://github.com/lra/mackup/blob/master/CONTRIBUTING.md

Also, what's in this folder? Can you `ls -l` it?

**Comment by bartoszj** [comment]
Folder content:
```
total 0
drwxr-xr-x@ 3 bjanda  staff  102 19 sie 19:27 Alcatraz.xcplugin
drwx------@ 3 bjanda  staff  102 19 sie 19:09 Backlight.xcplugin
drwx------@ 3 bjanda  staff  102 19 sie 19:09 ClangFormat.xcplugin
drwx------@ 3 bjanda  staff  102 19 sie 19:09 FuzzyAutocomplete.xcplugin
drwx------@ 3 bjanda  staff  102 19 sie 19:09 HOStringSense.xcplugin
drwx------@ 3 bjanda  staff  102 19 sie 19:09 KSImageNamed.xcplugin
drwx------@ 3 bjanda  staff  102 19 sie 19:09 MCLog.xcplugin
drwx------@ 3 bjanda  staff  102 19 sie 19:09 OMColorSense.xcplugin
drwx------@ 3 bjanda  staff  102 19 sie 19:09 OMQuickHelp.xcplugin
drwx------@ 3 bjanda  staff  102 19 sie 19:09 OpenInTerminal.xcplugin
drwx------@ 3 bjanda  staff  102 19 sie 19:09 SCXcodeSwitchExpander.xcplugin
drwx------@ 3 bjanda  staff  102 19 sie 19:09 UncrustifyPlugin.xcplugin
drwx------@ 3 bjanda  staff  102 19 sie 19:09 VVDocumenter-Xcode.xcplugin
drwx------@ 3 bjanda  staff  102 19 sie 19:09 XcodeColors.xcplugin
```

Sorry for not reading `CONTRIBUTING.md`. I hope I've updated everything.

**Comment by lra** [comment]
This is a lot of directories. What each directory contains?
We want to be sure to sync config and not data.

**Comment by bartoszj** [comment]
This is a full list of files. All the plugins have to be installed by the user, so number of folders will be different for each user.
I think that I've a lot of plugins, and the total size of this folder is only 6.1 MB. Other users who doesn't use Xcode or users who have never installed any Xcode plugin will have an empty folder. Please also note that configurations for applications like AppCode, PyCharm also backups plugins in binary format.
```
├── Alcatraz.xcplugin
│   └── Contents
│       ├── Info.plist
│       ├── MacOS
│       │   └── Alcatraz
│       └── Resources
│           ├── ATZPackageListTableCellView.nib
│           ├── ATZPluginWindowController.nib
│           ├── bitbucket_grayscale.tiff
│           ├── en.lproj
│           │   ├── InfoPlist.strings
│           │   └── Localizable.strings
│           ├── eye_icon.tiff
│           ├── git_grayscale.tiff
│           ├── github_grayscale.tiff
│           └── link_icon.tiff
├── Backlight.xcplugin
│   └── Contents
│       ├── Info.plist
│       ├── MacOS
│       │   └── Backlight
│       └── Resources
│           └── en.lproj
│               └── InfoPlist.strings
├── ClangFormat.xcplugin
│   └── Contents
│       ├── Info.plist
│       ├── MacOS
│       │   └── ClangFormat
│       └── Resources
│           ├── clang-format
│           └── en.lproj
│               └── InfoPlist.strings
├── FuzzyAutocomplete.xcplugin
│   └── Contents
│       ├── Info.plist
│       ├── MacOS
│       │   └── FuzzyAutocomplete
│       └── Resources
│           ├── FASettingsWindow.nib
│           └── en.lproj
│               └── InfoPlist.strings
├── HOStringSense.xcplugin
│   └── Contents
│       ├── Info.plist
│       └── MacOS
│           └── HOStringSense
├── KSImageNamed.xcplugin
│   └── Contents
│       ├── Info.plist
│       ├── MacOS
│       │   └── KSImageNamed
│       └── Resources
│           ├── Completions.plist
│           └── en.lproj
│               └── InfoPlist.strings
├── MCLog.xcplugin
│   └── Contents
│       ├── Info.plist
│       ├── MacOS
│       │   └── MCLog
│       └── Resources
│           └── en.lproj
│               └── InfoPlist.strings
├── OMColorSense.xcplugin
│   └── Contents
│       ├── Info.plist
│       └── MacOS
│           └── OMColorSense
├── OMQuickHelp.xcplugin
│   └── Contents
│       ├── Info.plist
│       └── MacOS
│           └── OMQuickHelp
├── OpenInTerminal.xcplugin
│   └── Contents
│       ├── Info.plist
│       ├── MacOS
│       │   └── OpenInTerminal
│       └── Resources
│           ├── LICENSE
│           ├── README.md
│           └── en.lproj
│               └── InfoPlist.strings
├── SCXcodeSwitchExpander.xcplugin
│   └── Contents
│       ├── Info.plist
│       └── MacOS
│           └── SCXcodeSwitchExpander
├── UncrustifyPlugin.xcplugin
│   └── Contents
│       ├── Info.plist
│       ├── MacOS
│       │   └── UncrustifyPlugin
│       └── Resources
│           ├── XCFPreferencesWindowController.nib
│           ├── clang-format
│           ├── icon.icns
│           └── uncrustify
├── VVDocumenter-Xcode.xcplugin
│   └── Contents
│       ├── Info.plist
│       ├── MacOS
│       │   └── VVDocumenter-Xcode
│       └── Resources
│           ├── VVDSettingPanelWindowController.nib
│           └── en.lproj
│               └── InfoPlist.strings
└── XcodeColors.xcplugin
    └── Contents
        ├── Info.plist
        ├── MacOS
        │   └── XcodeColors
        └── Resources
            └── English.lproj
                └── InfoPlist.strings
```

**Comment by lra** [comment]
ok thanks

**Pull request merged**
