### PR TITLE
added support for tweetbot

### PR DESCRIPTION
**Pull request by vitorgalvao**
Since it’s under `Library/Containers`, and syncing directories, this probably should wait until `mackup` can handle that.

### CODE REVIEW

**Comment by lucaorio** [comment]
@vitorgalvao man is there any news about this?

**Comment by vitorgalvao** [comment]
@lucaorio Nope, nothing I can do. Mackup [doesn’t support MAS apps](https://github.com/lra/mackup/issues/154) [because it relies on symlinking](https://github.com/lra/mackup/issues/195).

The project seems mostly abandoned feature-wise, so I somehow doubt it’ll happen. At least not without a PR.

**Comment by lra** [comment]
not really abandoned, I just need people to contribute =)

**Comment by vitorgalvao** [comment]
> not really abandoned, I just need people to contribute =)

Well, like I said:

> The project seems mostly abandoned feature-wise, so I somehow doubt it’ll happen. **At least not without a PR**.

So, same thing. If none of the core maintainers (you alone, I believe) is working on adding features, then the project is indeed effectively abandoned feature-wise. Wishing people contribute is very different than having said contribution.

**Comment by vitorgalvao** [comment]
To be clear, I’m not criticising you not adding features. It’s your project, and as with the [multiple ssh issues](https://github.com/lra/mackup/search?q=ssh&type=Issues&utf8=%E2%9C%93), it seems to me you have it working perfectly well for your exact needs and hence have no further incentive to keep adding to or changing it, *which is totally valid*.

[Having said that](http://youtu.be/ENHVQ2gslp8), that is not what you’re saying. Issues are left to linger, and requests aren’t refused or responded to with “I won’t do it, but will accept a contribution for it”, so users rightly get the impression those things are indeed being taken into consideration and worked on, which is not the case.

**Comment by lra** [comment]
I'm not against the copy feature or ssh default exclusion, but people are jumping on those while they require some other changes before, listed in the TODO.

You can't just change Mackup to optionally have a copy mode or exclude by default for ssh and not for the others in its current state. It will just make it super complex to use as some behavior will change depending on the mode or the application. It's already too complex too use IMO and it will just scare people away or generate issues with messed up configurations.

Any PR or help is welcome. Even issues to discuss the what and how to do some.

Regarding contributors, I'm def open to it, but I'm looking for code contributions here. Can't grant people just based on intention. https://github.com/lra/mackup/graphs/contributors

**Comment by vitorgalvao** [comment]
Most of that was addressed in my previous comments. Quite frankly, I have little interest in continuing down this conversation since I always make a huge effort to be respectful in pointing out what I think is wrong here but am always faced with what feels like a defensive take and answers to points I never made.

My take on it is (I believe) very clear: it is perfectly OK for you to not work on the project and everything that is asked, but you don’t say it. Issues are left open, *including* ***numerous*** *duplicates* without reply or acknowledgement for a long time (*or ever*). I’m certain there are capable users that would take on the job of submitting PRs for what is needed, *but if you don’t participate on the discussion of what you believe should be included* ***and how to implement it*** *why would anyone else*?

PRs won’t happen simply because there’s a TODO. Contributors need to feel their ideas will be at the very least considered (even if immediately refused) and that there is a point to spending time on them. If you don’t participate, they never do, and move on.

**Comment by lra** [comment]
I'm sorry if this is what is perceived. You make a good point managing the PRs and issues: it also warrants some attention.

Some help here would be appreciated. Also to point out those that lack some feedback, direction or approval to get going. BTW the existing issue/PR organization can be totally revamped.

I can add you if you are interested as you've been a long time help.

**Comment by vitorgalvao** [comment]
I appreciate the offer, but I honestly do not think I’d be a good candidate for that as I stopped using mackup, since syncing instead of copying broke too many things for me. For that reason I don’t check back as often, and you’d be back at square one.

I’m still up for helping with unifying the configs into a common repo/format, as we’ve talked about other times, though.

I do however recommend that when you engage with the issues, keep and eye out for a user that frequently participates, and “promote” that one to that position. Many times giving people the extra responsibility makes them work even more to earn it (in homebrew-cask we have examples).

**Comment by lra** [comment]
As you want, but know that I'm not asking you to be active. If you want to spend some time on it when you feel like it that'd be fine. It's not like we are limited in the number of contributors =)

**Comment by lra** [comment]
Depends on https://github.com/lra/mackup/issues/615

**Comment by vitorgalvao** [comment]
Closing as part of personal cleanup of old pull requests and issues. There’s no fix in sight (which is fine) and I have long stopped using mackup, so no point in keeping it open. #615 as links to all these, so they won’t be lost.

Please do let me know if you need something from these.

**Pull request closed without merging**
