### PR TITLE
Avoid backup on whole .docker folder (that could contain docker machi…

### PR DESCRIPTION
**Pull request by gdraynz**
…nes)

### CODE REVIEW

**Comment by darcy** [comment]
👍

**Comment by dr-impossible** [comment]
+1

**Comment by matti** [comment]
`.docker/config.json` contains authentication tokens. Is this allowed or not? `CONTRIBUTING.MD` says `Do not sync sensitive information, like clear passwords or private keys`

I'd say that let people sync what they want, but what's the policy here?

**Comment by matti** [comment]
Same goes to s3cmd. Are tokens considered private keys? @lra ?

**Comment by dr-impossible** [comment]
The AWS secrecy key definitely is. The AWS console reveals it only when you
first create the key pair and then never again.

**Pull request merged**
