### PR TITLE
sync .gitignore and .gitignore_global

### PR DESCRIPTION
**Pull request by ryoppippi**

### CODE REVIEW

**Comment by jamiew** [comment]
I haven't seen a `~/.gitignore_global` before, is that just an alternative configuration or a custom setup? `git config --global core.excludesfile` by default is `~/.gitignore`

I might recommend keeping that in a custom ~/.mackup/ config if it is a custom thing

**Comment by ryoppippi** [comment]
I see
Okay I’ll close this

**Comment by jamiew** [comment]
The `~/.gitignore` seems useful, I was just asking about `~/.gitignore_global`! Sorry if I was terse

It looks like we used to support `.gitignore` but no longer? https://github.com/lra/mackup/blob/master/mackup/applications/git.cfg

**Comment by lra** [comment]
It's been brought back multiple times: https://github.com/lra/mackup/pull/926#issuecomment-273964314

**Pull request closed without merging**
