### PR TITLE
Add support for Mac OS X Terminal

### PR DESCRIPTION
**Pull request by ryanjbonnell**

### CODE REVIEW

**Comment by nuno-agostinho** [comment]
+1

**Comment by oillio** [comment]
+1

**Comment by lra** [comment]
Can anyone confirm that this indeed works? Usually Apple stuff does not like symlinks and overwrite them.

**Comment by ryanjbonnell** [comment]
I've been dogfooding a [custom configuration][1] &mdash; with a symlinked Terminal preference file &mdash; on three different machines synced to Dropbox since I submitted the pull request nearly ~3 months ago and haven't had any issues.

I'm surprised there hasn't been more interest in this pull request though. All machines have been running Mac OS X 10.11.x "El Capitan".

[1]: https://github.com/ryanjbonnell/mackup/blob/24e72293d0d59ee4aa6409dc7ccee7074d33d751/mackup/applications/terminal.cfg

**Comment by pvinis** [comment]
@ryanjbonnell have you tried iTerm-nightly?

**Comment by reitermarkus** [comment]
I can also confirm this works, I have been using this for about a year now without any issues.

**Comment by leesiongchan** [comment]
Is this safe to be merged yet? Doesn't seem to have any issue either.

**Comment by matti** [comment]
This doesn't work for me. Terminal overwrites the symlink every time.

**Comment by lra** [comment]
@ryanjbonnell @reitermarkus you said it works. @matti should I revert this?

**Comment by matti** [comment]
I tested on two El Capitan installations and it doesn't work. 

Let's wait for comments?

**Comment by lra** [comment]
The thing is that I don't want to make a release with a conf that does not especially, especially how cumbersome it's for a user to upgrade a mackup that remove support for an app =/

**Comment by reitermarkus** [comment]
It's still working for me.

**Comment by matti** [comment]
```
$ ls -la Library/Preferences/com.apple.Terminal.plist
lrwxr-xr-x  1 mpa  staff  70 Aug 24 00:36 Library/Preferences/com.apple.Terminal.plist -> /Users/mpa/Dropbox/Mackup/Library/Preferences/com.apple.Terminal.plist
```

close Terminal and open it again (or open a new window):

```
ls -la Library/Preferences/com.apple.Terminal.plist   
-rw-------  1 mpa  staff  17611 Aug 24 00:38 Library/Preferences/com.apple.Terminal.plist
```

Opening a new tab doesn't overwrite the file.

This is my third mac with el capitan... I do believe that it works for others, just don't understand why.

**Comment by leesiongchan** [comment]
Mine is working fine too, El Capitan with latest 10.11.6.

**Comment by lra** [comment]
@reitermarkus @leesiongchan can you try what @matti did?

**Comment by reitermarkus** [comment]
```
 $ ls -la ~/Library/Preferences/com.apple.Terminal.plist
lrwxr-xr-x 1 Markus staff 73 Dez 22  2015 /Users/Markus/Library/Preferences/com.apple.Terminal.plist -> /Users/Markus/Dropbox/Sync/~/Library/Preferences/com.apple.Terminal.plist
```

Same after closing and re-opening Terminal.

**Comment by ryanjbonnell** [comment]
Mine is working just fine with Mackup 0.8.14 and Mac OS X "El Capitan" 10.11.6

**Comment by bdlow** [comment]
As of 10.12.6 (and I suspect earlier), Terminal replaces the symlink with a copy of the file. i.e. mackup's approach can't work for the plist file.

```
% sw_vers      
ProductName:	Mac OS X
ProductVersion:	10.12.6
BuildVersion:	16G29

% mackup restore
Restoring Library/Preferences/com.apple.Terminal.plist ...
You already have a file named Library/Preferences/com.apple.Terminal.plist in your home.
Do you want to replace it with your backup ? <Yes|No>yes
% readlink ~/Library/Preferences/com.apple.Terminal.plist
/Users/ben/Google Drive/Mackup/Library/Preferences/com.apple.Terminal.plist

```
- Terminal > Quit
- reopen Terminal

```
% readlink ~/Library/Preferences/com.apple.Terminal.plist 
% ls -l ~/Library/Preferences/com.apple.Terminal.plist
-rw-------  1 ben  staff  17454  8 Oct 21:48 /Users/ben/Library/Preferences/com.apple.Terminal.plist
```

**Pull request merged**
