### PR TITLE
add kindaVim

### PR DESCRIPTION
**Pull request by godbout**
### All submissions

* [x] I have followed the [Contributing Guidelines](https://github.com/lra/mackup/blob/master/.github/CONTRIBUTING.md)
* [x] I have checked to ensure there aren't other open [Pull Requests](https://github.com/lra/mackup/pulls) for the same update/change

### Adding/updating Application X Support

* [x] This PR is only for one application
* [x] It has been added to the list of supported applications in the [README](https://github.com/lra/mackup/blob/master/README.md)
* [x] Changes have been added to the WIP section of the [CHANGELOG](https://github.com/lra/mackup/blob/master/CHANGELOG.md)
* [x] Syncing does not break the application
* [x] Syncing does not compete with any syncing functionality internal to the application
* [x] The configuration syncs the minimal set of data
* [x] No file specific to the local workstation is synced
* [x] No sensitive data is synced

### Improving the Mackup codebase

* [ ] My submission passes the [tests](https://github.com/lra/mackup/tree/master/tests)
* [ ] I have linted the code locally prior to submission
* [ ] I have written new tests as applicable
* [ ] I have added an explanation of what the changes do

### CODE REVIEW

**Comment by godbout** [comment]
hi. anything i need to do to get this PR merged? i keep rebasing it now and then when i check if it's merged or not. thanks!

**Comment by godbout** [comment]
@lra quick question if you don't mind. does this need a new mackup release to be taken into consideration? or is there another mechanism. i see last release is from 2021. apologies if that's a dumb question. but that's because i'm dumb.

**Comment by joshmedeski** [comment]
@godbout not a dumb question but yes, you will need to wait for a release if you're using homebrew for this PR to take effect. You can also clone the project and run mackup manually until then.

**Comment by godbout** [comment]
@joshmedeski totally makes sense, thanks. yeah that was kinda dumb of me to assume the question was dumb. i've been using mackup personally for a long time but i'm now referring users of my apps so that they can save my apps' configs. so i guess release we will wait. thanks again!

**Comment by lra** [comment]
I usually do a release when someone asks for it, I'll do one today ;)

**Comment by godbout** [comment]
ahhhhhh i see. got it. greatly appreciated. thanks a lot!

**Pull request merged**
