### PR TITLE
Add support for PyCharm 2020 (versions 2, 3, 4) on macOS

### PR DESCRIPTION
**Pull request by ameyuuno**

### CODE REVIEW

**Comment by ameyuuno** [comment]
@lra 
Hello. Could you review PR? ^_^

**Review by harens — CHANGES_REQUESTED** [review]
Looks good to me. It might help if you [squash your commits](https://gist.github.com/patik/b8a9dc5cd356f9f6f980).

**Comment by ameyuuno** [comment]
@harens 
done) now there is only one commit

**Review by harens — APPROVED** [review]

**Comment by harens** [comment]
Just rename your commit message. Thanks @ameyuuno

**Comment by ameyuuno** [comment]
updated commit message

**Comment by ameyuuno** [comment]
@harens could you approve PR?

**Comment by harens** [comment]
I've approved it, but I can't merge it. I'm just a random GitHub user that thought I'd help! 😉

**Comment by ameyuuno** [comment]
Oh... Anyway thank you))

**Comment by harens** [comment]
It still says I've approved it, but only @lra has write access. All I can do is help speed up the process!

**Review by rhangelxs — APPROVED** [review]

**Review by lra — APPROVED** [review]
Thanks, I'll sort the lines

**Comment by lra** [comment]
https://github.com/lra/mackup/commit/af7817999a9c402c43a54711ab0f21bb21222c77

**Pull request merged**
