### PR TITLE
Add support for brave browser

### PR DESCRIPTION
**Pull request by cbenv**
Syncs [Brave Browser](https://brave.com/) preferences and nothing else. Very minimal footprint.

### CODE REVIEW

**Comment by lra** [comment]
Isn't there a cloud sync in Brave?

**Comment by cbenv** [comment]
There is something similar, setting can be synced (in p2p fashion afaik) with other clients but that feature is currently disabled ([ref](https://community.brave.com/t/brave-sync-temporarily-disabled-on-desktop/106837)). 

`Library/Application Support/BraveSoftware/Brave-Browser/Default/Preferences` is not a folder but a file whose content type is JSON. See below for sample (some fields are omitted)
```
{
  "account_id_migration_state": 2,
  "account_tracker_service_last_update": "13236146802007821",
  "announcement_notification_service_first_run_time": "13236146800827001",
  "apps": {
    "shortcuts_version": 6
  },
  "autocomplete": {
    "retention_policy_last_version": 81
  },
  "autofill": {
    "credit_card_enabled": false,
    "orphan_rows_removed": true,
    "profile_enabled": false
  },
  "bookmark_bar": {
    "show_on_all_tabs": true
  },
  "brave": {
    "branded_wallpaper_notification_dismissed": true,
    "brave_ads": {
      "ads_per_day": "20",
      "ads_per_hour": "2",
      "enabled": true,
      "has_p3a_state": true,
      "idle_threshold": 15,
      "prefs": {
        "version": 7
      },
      "should_allow_ad_conversion_tracking": true,
      "should_show_first_launch_notification": false,
      "should_show_my_first_ad_notification": true,
      "supported_regions_last_schema_version_number": 0,
      "supported_regions_schema_version_number": 8,
      "were_disabled": false
    },
    "fb_embed_default": false,
    "google_login_default": false,
    "linkedin_embed_default": true,
    "new_tab_page": {
      "show_binance": false,
      "show_branded_background_image": true,
      "show_stats": false,
      "show_top_sites": false
    },
    "other_bookmarks_migrated": true,
    "rewards": {
      "enabled": true,
      "enabled_migrated": true,
      "external_wallets": {...},
      "notifications": "{\"displayed\":[],\"notifications\":[]}",
      "promotion_last_fetch_stamp": "1591684816",
      "server_publisher_list_stamp": "1591673980"
    },
    "shields": {
      "advanced_view_enabled": true
    },
    "shields_settings_version": 2,
    "stats": {
      "ads_blocked": "1075",
      "bandwidth_saved_bytes": "48785596",
      "daily_saving_predictions_bytes": [
        {
          "day": 1591599600,
          "value": 48785596
        }
      ],
      "https_upgrades": "9"
    },
    "twitter_embed_default": true,
    "wallet": {
      "pref_version": 1,
      "web3_provider": 0
    },
    "webtorrent_enabled": false,
    "weekly_storage": {
      "search_count": [
        {
          "day": 1591599600,
          "value": 31
        }
      ]
    }
  },
  "browser": {
    "has_seen_welcome_page": true,
    "window_placement": {
      "bottom": 1050,
      "left": 0,
      "maximized": false,
      "right": 1680,
      "top": 23,
      "work_area_bottom": 1050,
      "work_area_left": 0,
      "work_area_right": 1680,
      "work_area_top": 23
    }
  },
  "countryid_at_install": 21843,
  "credentials_enable_service": false,
  "data_reduction": {
    "daily_original_length": [...],
    "daily_received_length": [...],
    "last_update_date": "13236073200000000",
    "network_properties": {},
    "this_week_number": 2631,
    "this_week_services_downstream_foreground_kb": {...}
  },
  "default_apps_install_state": 3,
  "domain_diversity": {
    "last_reporting_timestamp": "13236146809583499"
  },
  "download": {
    "directory_upgrade": true
  },
  "enable_do_not_track": true,
  "extensions": {...},
  "gcm": {
    "product_category_for_subtypes": "com.brave.macosx"
  },
  "google": {
    "services": {
      "signin_scoped_device_id": "..."
    }
  },
  "http_original_content_length": "50638373",
  "http_received_content_length": "50638373",
  "invalidation": {
    "per_sender_topics_to_handler": {...}
  },
  "language_model_counters": {
    "en": 215
  },
  "media": {
    "device_id_salt": "...",
    "engagement": {
      "schema_version": 4
    }
  },
  "media_router": {
    "enable_media_router": false,
    "receiver_id_hash_token": "..."
  },
  "ntp": {
    "app_page_names": [
      "Apps"
    ],
    "custom_background_local_to_device": false,
    "num_personal_suggestions": 4
  },
  "payments": {
    "can_make_payment_enabled": false
  },
  "plugins": {
    "plugins_list": []
  },
  "previews": {
    "litepage": {
      "user-needs-notification": false
    },
    "offline_helper": {
      "available_pages": {}
    }
  },
  "profile": {
    "avatar_bubble_tutorial_shown": 2,
    "avatar_index": 26,
    "block_third_party_cookies": true,
    "content_settings": {...},
    "created_by_version": "81.1.9.80",
    "default_content_setting_values": {
      "cookies": 1
    },
    "exit_type": "Crashed",
    "exited_cleanly": true,
    "last_engagement_time": "13236158549091717",
    "last_time_obsolete_http_credentials_removed": 1591673260.867355,
    "managed_user_id": "",
    "name": "Profile 1",
    "password_manager_onboarding_state": 1
  },
  "savefile": {
    "default_directory": "..."
  },
  "signin": {
    "DiceMigrationComplete": true,
    "allowed": false
  },
  "spellcheck": {
    "dictionaries": [
      "en-US"
    ]
  },
  "translate_site_blacklist_with_time": {},
  "updateclientdata": {
    "apps": {...}
  },
  "web_apps": {
    "system_web_app_last_installed_language": "en-US",
    "system_web_app_last_update": "81.1.9.80"
  },
  "webauthn": {
    "touchid": {
      "metadata_secret": "..."
    }
  }
}
```

**Comment by lra** [comment]
If sync is just temporary disabled, you might want to add this file to your mackup installation instead of making it part of the mackup distribution, no?

**Comment by cbenv** [comment]
Sorry, I do not understand your point. Do you not want mackup to support more applications? 

Also, brave sync is really meant to sync your settings across devices, there is no "brave account" you can retrieve your settings from. And right now it is disabled on desktop, so I see there is value to have mackup supports this.

**Comment by lra** [comment]
> Sorry, I do not understand your point. Do you not want mackup to support more applications?

Yes, but I don't want Mackup to overwrite and sync a setting that's already synced by an application. It can also conflict. What in this preferences folder is not sync by Brave itself?

> Also, brave sync is really meant to sync your settings across devices, there is no "brave account" you can retrieve your settings from.

Yes, this is a valid point. If you remove all you Brave apps, you lost you brave settings?

> And right now it is disabled on desktop, so I see there is value to have mackup supports this.

That's the thing, if it's temporary, and usually not needed, it's a good use case for a personal config.

**Comment by cbenv** [comment]
> I don't want Mackup to overwrite and sync a setting that's already synced by an application

I see. This was not my impression given that there are applications included in mackup distribution that already support native sync (e.g. jetbrains suite).

Anyway, I was able to force enable the sync feature and test that across multiple desktops. It appears that it does not sync preferences at all, only bookmarks. Bookmarks are stored in different file, namely `Library/Application Support/BraveSoftware/Brave-Browser/Default/Bookmarks`

Screen Shot 2020-06-12 at 5 25 51 PM

**Comment by lra** [comment]
> I see. This was not my impression given that there are applications included in mackup distribution that already support native sync (e.g. jetbrains suite).

I'm not aware of this, sorry, I have to trust contributors.

Thanks for digging, I'll merge.

**Pull request merged**
