### PR TITLE
Update the config dir path

### PR DESCRIPTION
**Pull request by GentleHoneyLover**
To comply with XDG Base Directory specification: https://wiki.archlinux.org/index.php/XDG_Base_Directory

### CODE REVIEW

**Comment by joshmedeski** [comment]
I support this change, however, there would have to be a clear way to migrate existing setups (my `.mackup` folder and config file are in the home directory right now).

I believe this would create a problem for people who already have mackup running on their computer.

**Comment by GentleHoneyLover** [comment]
> I support this change, however, there would have to be a clear way to migrate existing setups (my `.mackup` folder and config file are in the home directory right now).
> 
> I believe this would create a problem for people who already have mackup running on their computer.

I'm not a coder so cannot offer a ready solution, but could it be a little migration script as a part mackup that silently moves the config folder and config file to the new location at first run?

Or alternatively, maybe add two locations for config files (legacy location and new location) so that mockup looks for them in both places?

If I knew python I bit better, I could've sent a pull request for this :)

**Comment by joshmedeski** [comment]
We'll have to see what @lra thinks of this change. I'm comfortable with making a pull request but I want to see if he approves of this change before I take the time to work on it.

**Comment by GentleHoneyLover** [comment]
@joshmedeski, @Ira, is there an appetite to work on this further?

**Comment by yamatsum** [comment]
@joshmedeski 
@lra seems to agree to set up mackup with XDG Base Directory.
https://github.com/lra/mackup/issues/1317#issuecomment-460076807

**Comment by tshu-w** [comment]
vote for this

**Pull request closed without merging**
