### PR TITLE
Add possibility to colourize output and set up colours in config file

### PR DESCRIPTION
**Pull request by grigorii-horos**
Now mackup look like this:
image

### CODE REVIEW

**Comment by horosgrisa** [comment]
Thank you for accept of my code. I will improve it, will add another colourizations, and will add documentation.

Another question is: are you sure you want to support Python 2.7?

**Comment by horosgrisa** [comment]
@lra Can you help me with this error? 
```
Error: Unable to find your Dropbox install =(
```

**Comment by lra** [comment]
> are you sure you want to support Python 2.7?

I'd love not to. But that's what MacOS has.

**Comment by horosgrisa** [comment]
@lra Check https://github.com/lra/mackup/pull/1587/checks?check_run_id=744987768
Section:  Run make test

**Comment by lra** [comment]
Update your branch with master?

**Comment by grigorii-horos** [comment]
@lra Please, help me with GitHub tests.

**Pull request closed without merging**
