### PR TITLE
Add storage engine for Google Drive File Stream

### LINKED ISSUE #1082: Google Drive Replaced
Google recently replaced Google Drive with Google Drive File Stream. This is causing the following (obvious) error 

```terminal 
$ mackup list
Error: Unable to find your Google Drive install =(
```
I tried a system link with no luck.

### PR DESCRIPTION
**Pull request by MikaelSmith**
Adds a storage engine for Google Drive File Stream, the team-based
replacement for Google Drive. Currently hard-coded to `$HOME/Google
Drive File Stream/My Drive`, as the location doesn't seem to be
configurable in File Stream.

Also update the README for Box and iCloud.

Fixes #1082.

### CODE REVIEW

**Comment by MikaelSmith** [comment]
This works, but I'm not sure I'd recommend using it. File Stream seems to have some trouble with browsing stuff even if it's "Available offline", and seems slow to sync changes back.

**Comment by MikaelSmith** [comment]
Closing as it didn't work very well and no one seems interested.

**Comment by lra** [comment]
I'm not sure no one is interested, but it did not work well?

**Comment by lra** [comment]
Ok, let's keep the PR archived in case it sparks interest in the future.

**Comment by jags613** [comment]
+1 interest.
Any chance of getting this working well with G FileStream?

**Comment by mackoz** [comment]
+1 interest

**Comment by Kyrluckechuck** [comment]
+1 interest!

**Comment by pburkindine** [comment]
+1 Current support is out of date, see @MikaelSmith 's comment here for workaround

https://github.com/lra/mackup/issues/1082#issuecomment-383313659

**Comment by borland502** [comment]
I'll note that the default installation dir has changed.  It is now

```
[storage]
engine = file_system
path = Google Drive/My Drive
```

**Comment by drkdw** [comment]
> I'll note that the default installation dir has changed. It is now
> 
> ```
> [storage]
> engine = file_system
> path = Google Drive/My Drive
> ```
> 
> Oh, and for God's sake flag "offline access" in Finder!

Thanks! Was looking for a way to use Google Drive. To bad docs isn't up to date.

**Pull request closed without merging**
