### PR TITLE
Utils.py tests - 97% coverage

### PR DESCRIPTION
**Pull request by Timidger**
These are tests for most of the functions in Utils.py. I wasn't able to get to `remove_acl` or `remove_immutable_attribute` because I could not find an elegant way to do that across operating systems without resorting to using `subprocess.call`.

### CODE REVIEW

**Comment by lra** [comment]
Cool stuff =)
But:
```
[analogue:~/src/mackup] Timidger-UtilsTest 14s ± nosetests
.............Fchflags: /var/folders/d5/tj5tbxp912g9ftz5k44zhw1c0000gn/T/tmpBhBzX1/tmp0KtfAZ: Permission denied
chflags: /var/folders/d5/tj5tbxp912g9ftz5k44zhw1c0000gn/T/tmpBhBzX1: Permission denied
...............usage: the_program [-h] {backup,restore,uninstall,list}
the_program: error: argument mode: invalid choice: 'some wrong mode' (choose from 'backup', 'restore', 'uninstall', 'list')
.
======================================================================
FAIL: test_can_file_be_synced_on_current_platform (utils_test.TestMackup)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/analogue/src/mackup/tests/utils_test.py", line 350, in test_can_file_be_synced_on_current_platform
    assert not utils.can_file_be_synced_on_current_platform(path)
AssertionError: 
-------------------- >> begin captured stdout << ---------------------
/Users/analogue/src/mackup/tests/fixtures/Library/

--------------------- >> end captured stdout << ----------------------

----------------------------------------------------------------------
Ran 30 tests in 0.145s

FAILED (failures=1)
```

**Comment by Timidger** [comment]
Sorry about that. Print statement removed, and the test fixed so it works on OSx now :+1:

**Comment by lra** [comment]
Cool stuff, only issue left is:
```
[analogue:~/src/mackup] Timidger-UtilsTest ± nosetests
.............................usage: the_program [-h] {backup,restore,uninstall,list}
the_program: error: argument mode: invalid choice: 'some wrong mode' (choose from 'backup', 'restore', 'uninstall', 'list')
.
----------------------------------------------------------------------
Ran 30 tests in 0.057s

OK
```
We'd like to no have any useless output polluting the tests output results.

**Comment by Timidger** [comment]
Here we are. Sorry about the garbage output. On my 64-bit Linux machine, there is a bunch of `Inappropriate ioctl for device while reading flags` errors whenever I test it. For some reason it doesn't want to change the flags on the file in `/tmp`.
test-coverage

**Pull request merged**
