### PR TITLE
Add support for GoLand

### PR DESCRIPTION
**Pull request by rayrutjes**

### CODE REVIEW

**Comment by lra** [comment]
This is weird, do you know what JetBrain's Gogland is? See https://github.com/lra/mackup/blob/master/mackup/applications/gogland.cfg

**Comment by rayrutjes** [comment]
> This is weird, do you know what JetBrain's Gogland is? See 
I believe that was the previous name of their product.

**Comment by rayrutjes** [comment]
Maybe I could rename `gogland.cfg` -> `goland.cfg` and keep the gogland files for backward compat purposes?

**Comment by lra** [comment]
please do

**Comment by rayrutjes** [comment]
Done!

**Pull request merged**
