### PR TITLE
feat: trim inline and line comments out of config

### PR DESCRIPTION
**Pull request by joshmedeski**
Closes https://github.com/lra/mackup/issues/1832

Add support for inline comments or lined comments inside the config file.

- Abstracted get options function to trim inline comments and remove line comments from set
- Updated parsing functions with abstracted function
- Added inline comments and line comments to test config files (tests are passing!)

### All submissions

* [x] I have followed the [Contributing Guidelines](https://github.com/lra/mackup/blob/master/.github/CONTRIBUTING.md)
* [x] I have checked to ensure there aren't other open [Pull Requests](https://github.com/lra/mackup/pulls) for the same update/change

### Improving the Mackup codebase

* [x] My submission passes the [tests](https://github.com/lra/mackup/tree/master/tests)
* [x] I have linted the code locally prior to submission
* [x] I have written new tests as applicable
* [x] I have added an explanation of what the changes do

### CODE REVIEW

**Comment by joshmedeski** [comment]
@lra let me know if you want additional tests or want any refactoring done 😄

**Comment by joshmedeski** [comment]
Let me know if you want to merge this @lra, otherwise I'd prefer to close it.

**Comment by lra** [comment]
I don't understand as comments are already supported, no? https://docs.python.org/3/library/configparser.html#supported-ini-file-structure

**Comment by LucasLarson** [comment]
> comments are already supported

They are, but inline comments are not supported: https://github.com/lra/mackup/issues/1831#issuecomment-1144352035

**Comment by joshmedeski** [comment]
Correct, inline comments don't work without my code. If it's something we don't want to support I understand, it did cause an issue with one of our users so I made a quick patch to support it.

**Review by lra — COMMENTED** [review]
I see. Let's not reinvent the wheel and use the inline comment support from the python library instead, look for `inline_comment_prefixes` in https://docs.python.org/3/library/configparser.html

**Comment by joshmedeski** [comment]
Okay, I'll spend some more time investigating the docs and push some changes if needed, otherwise, we may just close this branch.

I agree that we don't want to reinvent something if it's already provided to us in a standard library.

**Comment by joshmedeski** [comment]
I got it working and opened a new PR, thanks for the feedback ❤️

**Pull request closed without merging**
