### PR TITLE
Add support for tilix

### PR DESCRIPTION
**Pull request by pat-s**
[Tilix](https://gnunn1.github.io/tilix-web/)

### CODE REVIEW

**Comment by pat-s** [comment]
Made the requested changes, sorry for missing initially. 

While at it, I also sorted the list if supported apps alphabetically. Is this ok or should I move it into a separate PR?

**Comment by lra** [comment]
Thanks.

Yeah, I'm not sure the ordering of the list makes total sense, if you move it out to a separate PR, I can merge this one immediately, up to you.

**Comment by pat-s** [comment]
Hm, somethings wrong with the README.md diff. I resetted to master (tilix entry still missing) and its still showing some diffs.

**Comment by lra** [comment]
`git checkout origin/master README.md`?

**Comment by pat-s** [comment]
First `git checkout master -- README.md`, after that even a complete copy/paste from the Github README.md into the PR. That's the origin of all the recent "Update README" commits.
Sorry, this small change becomes a mess - grml.

**Comment by lra** [comment]
That's fine, just mention me back once it's in a clean state.

**Comment by pat-s** [comment]
superseeded by #1302 	.

**Pull request closed without merging**
