### PR TITLE
Add snap support

### PR DESCRIPTION
**Pull request by guilhem**
More information on https://snapcraft.io/

To add auto-build please register repo on https://build.snapcraft.io/

### CODE REVIEW

**Comment by lra** [comment]
Thanks for this. Looks like the `mackup` name is already taken. I don't want to make the case more complex than it is and register another `mackup`. Do you now what's going on?

screen shot 2018-03-23 at 5 02 06 pm

**Comment by guilhem** [comment]
Yes I reserved name myself and send you an invitation before this day for you to became collaborator (before giving you full control).

**Comment by guilhem** [comment]
I work on this snap for quite some time :)

**Comment by lra** [comment]
got it! Anything else I need to do? Do I need to add a step to the [release.md](https://github.com/lra/mackup/blob/master/doc/release.md) doc? Or it needs to be snapped manually by the community on each new release, like homebrew?

**Comment by guilhem** [comment]
@lra look in https://build.snapcraft.io/ , you can link github webhook to build on edge channel.
Release on stable channel can be done on website easily or with Travis :)

**Comment by guilhem** [comment]
Oh also I put as version "git".
It use `git describe` to name version.
That a really good practice and behavior, but sadly `git describe` is some kind of broken on your repository and always put `0.5` as version.

**Comment by guilhem** [comment]
Ok I learn something on git today:
https://bugs.launchpad.net/snapcraft/+bug/1706724/comments/1

**Comment by lra** [comment]
Hi @guilhem 

I just merged it but I'm stuck as the name is already taken.
screen shot 2018-08-31 at 4 42 25 pm
Should I file a claim?

**Pull request merged**
