### PR TITLE
Add support for Calibre

### PR DESCRIPTION
**Pull request by ttuygun**

### CODE REVIEW

**Comment by fharper** [comment]
@ttuygun : are you able to make the changes and submit a new PR that can me merged please? I would love to have support for Calibre.

**Comment by ttuygun** [comment]
> Can you add an entry in the changelog?

What does it mean _changelog_

**Comment by pvinis** [comment]
https://github.com/lra/mackup/blob/master/CHANGELOG.md
Edit this file, and write what you added.

**Comment by lra** [comment]
Superseded by https://github.com/lra/mackup/pull/1527

**Pull request closed without merging**
