### PR TITLE
Add global gitignores

### PR DESCRIPTION
**Pull request by SamuelNitsche**

### CODE REVIEW

**Comment by lra** [comment]
The thing with those global git ignores is that those are not official (e.g. referenced in `git`'s source code).

Because of this, you should use a custom config to sync them, or we'll end up having to specify everyone's config in the official application configs.

**Comment by SamuelNitsche** [comment]
Thanks, I didn't know this. I have now created a separate file for the synchronization.

**Comment by lra** [comment]
Well, I don't know if I an accept this, "Gitignore" is an application. what I was saying is that you can use this file yourself by adding it into the `.mackup` folder per https://github.com/lra/mackup/tree/master/doc#add-support-for-an-application-or-any-file-or-directory

**Comment by SamuelNitsche** [comment]
Oh, now I see what you mean. I'm fine with this :) Thanks for your feedback!

**Pull request closed without merging**
