### PR TITLE
Add support for PhpStorm 9.5

### PR DESCRIPTION
**Pull request by mnapoli**

### CODE REVIEW

**Comment by lra** [comment]
https://github.com/lra/mackup/blob/master/CONTRIBUTING.md

**Comment by mnapoli** [comment]
Do you want a changelog entry? I wasn't sure if that was a change significant enough to warrant that so let me know if that's what you meant with the link.

**Comment by mnapoli** [comment]
Added changelog.

**Comment by lra** [comment]
thx =)
I wonder if we should merge all the versions at some point

**Comment by DS-Matt** [comment]
running mackup (0.8.12) and it doesn't seem to be backing up any of the files for PhpStorm 10.  Any ideas how to get this to start backing up?

**Comment by driesvints** [comment]
@DS-Matt support is on master but needs a release tag.

**Pull request merged**
