### PR TITLE
OSX Services Workflows

### PR DESCRIPTION
**Pull request by TCattd**
Example for what it's backing up
http://brettterpstra.com/howtos/install-an-os-x-system-service/

### CODE REVIEW

**Comment by TCattd** [comment]
Added two more things too:

- New Mailplane 3 path to backup.
- KeePassX 2 new file to backup.

;)

**Comment by TCattd** [comment]
- ...and Alfred 2 :)

**Comment by lra** [comment]
Please keep one PR per application, it's hard to work on multiple together
https://github.com/lra/mackup/blob/master/CONTRIBUTING.md

**Comment by TCattd** [comment]
Sorry. I let github to handle the PR, but the second one just was merged in the first PR automatically. Then i just added the other modifications and they appeared here too (i commented later). Sorry about that.

**Comment by zanderzhng** [comment]
Create a new branch if you don't want your commits to merge.
And alfred 2 already has builtin syncing, #405 , #127 , #116 .

**Pull request closed without merging**
