### PR TITLE
Add support for iTermocil

### PR DESCRIPTION
**Pull request by godbout**
iTermocil allows workspace setup through YAML files for iTerm2.

### CODE REVIEW

**Comment by godbout** [comment]
My bad. Will do.

**Comment by godbout** [comment]
Should be fine now, hopefully. Not very confident with updating pull requests. Let me know if there's something else I need to do. Thanks.

**Comment by MadeOfMagicAndWires** [comment]
Thanks! 

Don't worry about updating PRs, they're the same as any git branch and github is smart enough to update the actual request. Speaking of which, it's not required but your last commit is not signed, you might want to amend it and force a push, we need to wait for circleci to get fixed to merge anyway.

**Comment by godbout** [comment]
Huh. Weird. Will have a look, thanks for the help!

**Comment by godbout** [comment]
Ok, that was a bit more tricky than I thought. I've never had to sign commits before, I thought it was just an issue with my name/email 😂️

Should be ok now.

**Comment by MadeOfMagicAndWires** [comment]
Sorry, I'm super dumb.

I noticed your merging commit (29de7a6) was verified and just didn't realise you merged through github, thus thinking the key was yours.

Don't worry about it, it's really only something for when people need to be 100% certain it's you sending the commits, realistically no project will require you to sign every single commit, I just thought you were very security conscious. 

But at least you know how it works now :wink:

**Comment by godbout** [comment]
No worries, yeah new tools in my pocket, always good to have! Cheers.

**Pull request merged**
