### PR TITLE
Add Slack

### PR DESCRIPTION
**Pull request by sscotth**

### CODE REVIEW

**Comment by lra** [comment]
I don't have a `~/Library/Application Support/Slack` folder, do you know why?

**Comment by sscotth** [comment]
Weird. The directory is on all three of my macs that I use.

**Comment by bskrtich** [comment]
Could it be the difference of the App store version from the downloaded version?

**Comment by sscotth** [comment]
Looks like the MAS version, uses `~/Library/Containers/com.tinyspeck.slackmacgap/Data/Library/Application Support/Slack`

**Comment by sscotth** [comment]
Bump

**Comment by spuder** [comment]
I just tried using the slack backup to move to a new mac, and now slack won't open
```
--- slack ---
Restoring
  linking /Users/spencer.owen/Library/Containers/com.tinyspeck.slackmacgap/Data/Library/Application Support/Slack/storage/slack-appTeams
  to      /Users/spencer.owen/Dropbox/Mackup/Library/Containers/com.tinyspeck.slackmacgap/Data/Library/Application Support/Slack/storage/slack-appTeams ...
You already have a file named Library/Containers/com.tinyspeck.slackmacgap/Data/Library/Application Support/Slack/storage/slack-appTeams in your home.
Do you want to replace it with your backup ? <Yes|No>y
Restoring
  linking /Users/spencer.owen/Library/Containers/com.tinyspeck.slackmacgap/Data/Library/Application Support/Slack/storage/slack-settings
  to      /Users/spencer.owen/Dropbox/Mackup/Library/Containers/com.tinyspeck.slackmacgap/Data/Library/Application Support/Slack/storage/slack-settings ...
You already have a file named Library/Containers/com.tinyspeck.slackmacgap/Data/Library/Application Support/Slack/storage/slack-settings in your home.
Do you want to replace it with your backup ? <Yes|No>y
Doing nothing
  /Users/spencer.owen/Dropbox/Mackup/Library/Application Support/Slack/storage/slack-settings
  does not exist
Restoring
  linking /Users/spencer.owen/Library/Containers/com.tinyspeck.slackmacgap/Data/Library/Application Support/Slack/Cookies
  to      /Users/spencer.owen/Dropbox/Mackup/Library/Containers/com.tinyspeck.slackmacgap/Data/Library/Application Support/Slack/Cookies ...
You already have a file named Library/Containers/com.tinyspeck.slackmacgap/Data/Library/Application Support/Slack/Cookies in your home.
Do you want to replace it with your backup ? <Yes|No>y
Doing nothing
  /Users/spencer.owen/Dropbox/Mackup/Library/Application Support/Slack/storage/slack-appTeams
  does not exist
Doing nothing
  /Users/spencer.owen/Dropbox/Mackup/Library/Application Support/Slack/Cookies
  does not exist
Restoring
  linking /Users/spencer.owen/Library/Containers/com.tinyspeck.slackmacgap/Data/Library/Application Support/Slack/storage/slack-teams
  to      /Users/spencer.owen/Dropbox/Mackup/Library/Containers/com.tinyspeck.slackmacgap/Data/Library/Application Support/Slack/storage/slack-teams ...
You already have a file named Library/Containers/com.tinyspeck.slackmacgap/Data/Library/Application Support/Slack/storage/slack-teams in your home.
Do you want to replace it with your backup ? <Yes|No>y
Doing nothing
  /Users/spencer.owen/Dropbox/Mackup/Library/Application Support/Slack/storage/slack-teams
  does not exist
```

**Comment by sscotth** [comment]
Your error says: `/Users/spencer.owen/Dropbox/Mackup/Library/Application Support/Slack/storage/slack-settings does not exist`

Check to make sure your backup worked.

**Comment by spuder** [comment]
When installing from the appStore files are stored at

`~/Library/Containers/com.tinyspeck.slackmacapp`

When installing from the download, files are stored at

`~/Library/Application Support/Slack`

Hence the reason the error showed `slack-settings` does not exist. 

---

I've tried from scratch several more times with the same result. The process of backing up slack breaks the app on both the old laptop and the new laptop. 

Steps to reproduce

1. Close slack on old and new laptop
2. Run `mackup uninstall` to completely revert any mackup symlinks on old laptop 
3. Verify slack is able to open properly
4. Add the diff from this MR to ~/.mackup/slack.cfg` on old laptop
5. Remove any existing dropbox files at `Dropbox/Mackup/Library/Containers/com.tinyspeck.slackmacgap/*`
and
`Dropbox/Mackup/Library/Application Support/Slack/*`
(Since I installed from the app store, I only have files at the first location)
6. Run `mackup backup` on old laptop
7. Open slack

At this point slack becomes unusable on the old laptop


```
--- slack ---
Doing nothing
  /Users/spencer.owen/Library/Application Support/Slack/storage/slack-teams
  does not exist
Backing up
  /Users/spencer.owen/Library/Containers/com.tinyspeck.slackmacgap/Data/Library/Application Support/Slack/Cookies
  to
 /Users/spencer.owen/Dropbox/Mackup/Library/Containers/com.tinyspeck.slackmacgap/Data/Library/Application Support/Slack/Cookies ...
Backing up
  /Users/spencer.owen/Library/Containers/com.tinyspeck.slackmacgap/Data/Library/Application Support/Slack/storage/slack-teams
  to
 /Users/spencer.owen/Dropbox/Mackup/Library/Containers/com.tinyspeck.slackmacgap/Data/Library/Application Support/Slack/storage/slack-teams ...
Doing nothing
  /Users/spencer.owen/Library/Application Support/Slack/Cookies
  does not exist
Doing nothing
  /Users/spencer.owen/Library/Application Support/Slack/storage/slack-settings
  does not exist
Backing up
  /Users/spencer.owen/Library/Containers/com.tinyspeck.slackmacgap/Data/Library/Application Support/Slack/storage/slack-settings
  to
 /Users/spencer.owen/Dropbox/Mackup/Library/Containers/com.tinyspeck.slackmacgap/Data/Library/Application Support/Slack/storage/slack-settings ...
Doing nothing
  /Users/spencer.owen/Library/Application Support/Slack/storage/slack-appTeams
  does not exist
Backing up
  /Users/spencer.owen/Library/Containers/com.tinyspeck.slackmacgap/Data/Library/Application Support/Slack/storage/slack-appTeams
  to
 /Users/spencer.owen/Dropbox/Mackup/Library/Containers/com.tinyspeck.slackmacgap/Data/Library/Application Support/Slack/storage/slack-appTeams ...

```

The cause is that slack_helper is unable to start. The error console shows errors like:

```
error	11:55:33.462545 -0700	Slack	Unable to load Info.plist exceptions (eGPUOverrides)
default	11:55:33.463068 -0700	storeassetd	SoftwareMap: Warning: Spotlight told us to add an app that already exists. Ignoring: <CKSoftwareProduct: 0x7fb0ae411c80>: (com.tinyspeck.slackmacgap, 3.3.3, 803453959:828793611 VPP:NO md:0x7fb0b194eee0 /Applications/Slack.app)  : <CKSoftwareProduct: 0x7fb0b1b98240>: (com.tinyspeck.slackmacgap, 3.3.3, 803453959:828793611 VPP:NO md:0x7fb0b194eee0 /Applications/Slack.app)
default	11:55:33.474021 -0700	Slack	NSApp cache appearance:
-NSRequiresAquaSystemAppearance: 1
-appearance: (null)
-effectiveAppearance: <NSCompositeAppearance: 0x600001908b40
 (
    "<NSAquaAppearance: 0x600002c21f00>",
    "<NSSystemAppearance: 0x600002c22580>"
)>
default	11:55:33.536717 -0700	secinitd	Slack Helper[6960]: root path for bundle "<private>" of main executable "<private>"
default	11:55:33.548004 -0700	secinitd	Slack Helper[6960]: AppSandbox request successful
default	11:55:33.579327 -0700	kernel	AGC:: [Slack Helper pid:6960 mux-aware] starting, non-mux-aware app count 0 WS-ready 1 switch-state 0 IG FBs 0 EG FBs 1:1f power-state 0 3D idle HDA idle system-state 1 power-level 20:20 connect-change 0
default	11:55:33.609520 -0700	loginwindow	-[PersistentAppsSupport applicationReady:] | App: Slack, ready, updating active tracking timer
error	11:55:33.612730 -0700	Slack Helper	Unable to load Info.plist exceptions (eGPUOverrides)
default	11:55:33.638674 -0700	tccd	-[TCCDAccessIdentity staticCode]: static code for: identifier com.tinyspeck.slackmacgap, type: 0: 0x7f8121a0fff0 at /Applications/Slack.app
default	11:55:33.760932 -0700	Slack Helper	GVA info: preferred scaler idx 1
default	11:55:33.804087 -0700	Slack	no previous integrity acl exists; making a new one
default	11:55:33.816846 -0700	Slack	0x600001719400 commited /Users/spencer.owen/Library/Keychains/login.keychain-db.sb-1817490d-1V2jPM to /Users/spencer.owen/Library/Keychains/login.keychain-db
default	11:55:33.854788 -0700	Slack	0x600001710d80 commited /Users/spencer.owen/Library/Keychains/login.keychain-db.sb-1817490d-4oG89L to /Users/spencer.owen/Library/Keychains/login.keychain-db
default	11:55:33.865328 -0700	Slack	0x60000176c300 commited /Users/spencer.owen/Library/Keychains/login.keychain-db.sb-1817490d-9aOfj0 to /Users/spencer.owen/Library/Keychains/login.keychain-db
default	11:55:37.209270 -0700	Slack	27366555: RECEIVED OUT-OF-SEQUENCE NOTIFICATION: 1349 vs 1976, 513, <private>

default	11:55:38.613113 -0700	loginwindow	-[PersistentAppsSupport saveLogoutPersistentState:finalSnapshot:] |      checkAgainstApp is : Slack
default	11:55:38.613131 -0700	loginwindow	-[PersistentAppsSupport appShouldBeRelaunched:] | entered. checking app: Slack
default	11:55:38.613186 -0700	loginwindow	-[PersistentAppsSupport saveLogoutPersistentState:finalSnapshot:] |           Adding to relaunchArray: Slack

default	11:55:43.530717 -0700	Slack	LSExceptions shared instance invalidated for timeout.
default	11:55:43.632520 -0700	Slack Helper	LSExceptions shared instance invalidated for timeout.

```

I suspect slack_helper does not like symlinks or it is missing another important file

**Comment by sscotth** [comment]
But the error says the file is missing from your dropbox. I use the downloaded version, to the app store version.

When I run `mackup backup` on my machine it produces `Dropbox\Slack\Library\Application Support\Slack\...`

When I run `mackup restore` I get no error messages about the app store version

**Comment by lra** [comment]
> I'm not sure if there's a way for mackup to copy instead of symlinking.

There isn't, yet.

**Comment by treee111** [comment]
possible dublicate to: https://github.com/lra/mackup/pull/1241

**Pull request closed without merging**
