### PR TITLE
Add support for GIMP

### PR DESCRIPTION
**Pull request by mateusrevoredo**

### CODE REVIEW

**Comment by lra** [comment]
I'm scared that the synced folder is gonna have a lot of cache/binary stuff. Can you dig in?

**Comment by mateusrevoredo** [comment]
Yes!
In case the folder contains lots of unnecessary stuff, can I narrow the configuration file to only sync the absolutely necessary files?

**Comment by mateusrevoredo** [comment]
As you can see, the synced files are shortcuts, plugins, scripts, templates themes etc.All of those files are part of someone's configuration.
The only exception would be the temp folder. But it is only used when exporting an image. It creates a file and then deletes the file after the export operation ends.
In my Mac the folder currently “weighs” ~700 Kb.

gimp01
gimp02

**Comment by lra** [comment]
Try it locally and let us know.

**Comment by mateusrevoredo** [comment]
I've been using this for more than a week and it's working like expected.

**Comment by fharper** [comment]
@mateusrevoredo: any plans to update this PR and merge it?

**Pull request closed without merging**
