### PR TITLE
add homebrew support

### PR DESCRIPTION
**Pull request by exherb**

### CODE REVIEW

**Comment by exherb** [comment]
please review when got time, thanks

**Comment by lra** [comment]
Can you rename this to just Homebrew (https://brew.sh/)?
Looks like official support is now in:
Screen Shot 2020-08-27 at 9 30 34 AM

**Comment by exherb** [comment]
> Can you rename this to just Homebrew (https://brew.sh/)?
> Looks like official support is now in:
> Screen Shot 2020-08-27 at 9 30 34 AM

ok, done

**Review by lra — APPROVED** [review]
thx

**Pull request merged**
