### PR TITLE
store `DynamicProfiles` from `$XDG_CONFIG_HOME` (#1855)

### LINKED ISSUE #1855: iTerm2 DynamicProfiles FileExistsError
Im getting the following error when trying to backup iTerm2 DynamicProfiles:

```
Backing up Library/Application Support/iTerm2/DynamicProfiles ...
A folder named /Users/username/Library/Mobile Documents/com~apple~CloudDocs/Mackup/Library/Application Support/iTerm2/DynamicProfiles already exists in the backup.
Are you sure that you want to replace it? <Yes|No> Yes
Traceback (most recent call last):
  File "/opt/homebrew/bin/mackup", line 33, in <module>
    sys.exit(load_entry_point('mackup==0.8.35', 'console_scripts', 'mackup')())
  File "/opt/homebrew/Cellar/mackup/0.8.35/libexec/lib/python3.10/site-packages/mackup/main.py", line 93, in main
    app.backup()
  File "/opt/homebrew/Cellar/mackup/0.8.35/libexec/lib/python3.10/site-packages/mackup/application.py", line 114, in backup
    utils.link(mackup_filepath, home_filepath)
  File "/opt/homebrew/Cellar/mackup/0.8.35/libexec/lib/python3.10/site-packages/mackup/utils.py", line 145, in link
    os.symlink(target, link_to)
FileExistsError: [Errno 17] File exists: '/Users/username/Library/Mobile Documents/com~apple~CloudDocs/Mackup/Library/Application Support/iTerm2/DynamicProfiles' -> '/Users/username/Library/Application Support/iTerm2/DynamicProfiles'
```

Is this a bug or something on my side?

### PR DESCRIPTION
**Pull request by LucasLarson**
iTerm2’s `DynamicProfiles` content can be saved without error, but only if loaded from `$XDG_CONFIG_HOME/iterm2/AppSupport/DynamicProfiles` (instead of from `~/Library/Application Support/iTerm2/DynamicProfiles`).

Because this pull request will prevent new errors in backing up `DynamicProfiles`, it should <ins title="added after submitting pull request">be</ins> considered to fix #1855.

### All submissions

* [x] I have followed the [Contributing Guidelines](https://github.com/lra/mackup/blob/master/.github/CONTRIBUTING.md)
* [x] I have checked to ensure there aren't other open [Pull Requests](https://github.com/lra/mackup/pulls) for the same update/change

### Adding/updating Application X Support

* [x] This PR is only for one application
* [x] It has been added to the list of supported applications in the [README](https://github.com/lra/mackup/blob/master/README.md)
* [x] Changes have been added to the WIP section of the [CHANGELOG](https://github.com/lra/mackup/blob/master/CHANGELOG.md)
* [x] Syncing does not break the application
* [x] Syncing does not compete with any syncing functionality internal to the application
* [x] The configuration syncs the minimal set of data
* [x] No file specific to the local workstation is synced
* [x] No sensitive data is synced

### Improving the Mackup codebase

* [x] My submission passes the [tests](https://github.com/lra/mackup/tree/master/tests)
* [x] I have linted the code locally prior to submission
* [ ] I have written new tests as applicable
* [ ] I have added an explanation of what the changes do

### CODE REVIEW

**Review by ukn0who — COMMENTED** [review]
It should fix the issue.

**Review by lra — APPROVED** [review]
Thanks!

**Comment by elmpp** [comment]
I'm still getting the iterm2 specific error with latest release of `0.8.37`:

```
Backing up
  /Users/matt/Library/Preferences/com.googlecode.iterm2.plist
  to
  /Users/matt/Library/CloudStorage/GoogleDrive-matthew.penrice@gmail.com/My Drive/syncable_apps_mackup/Library/Preferences/com.googlecode.iterm2.plist ...
A file named /Users/matt/Library/CloudStorage/GoogleDrive-matthew.penrice@gmail.com/My Drive/syncable_apps_mackup/Library/Preferences/com.googlecode.iterm2.plist already exists in the backup.
Are you sure that you want to replace it? <Yes|No> yes
Backing up
  /Users/matt/.config/iterm2/AppSupport/DynamicProfiles
  to
  /Users/matt/Library/CloudStorage/GoogleDrive-matthew.penrice@gmail.com/My Drive/syncable_apps_mackup/.config/iterm2/AppSupport/DynamicProfiles ...
A folder named /Users/matt/Library/CloudStorage/GoogleDrive-matthew.penrice@gmail.com/My Drive/syncable_apps_mackup/.config/iterm2/AppSupport/DynamicProfiles already exists in the backup.
Are you sure that you want to replace it? <Yes|No> yes
Traceback (most recent call last):
  File "/usr/local/bin/mackup", line 33, in <module>
    sys.exit(load_entry_point('mackup==0.8.37', 'console_scripts', 'mackup')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/mackup/0.8.37/libexec/lib/python3.11/site-packages/mackup/main.py", line 93, in main
    app.backup()
  File "/usr/local/Cellar/mackup/0.8.37/libexec/lib/python3.11/site-packages/mackup/application.py", line 112, in backup
    utils.link(mackup_filepath, home_filepath)
  File "/usr/local/Cellar/mackup/0.8.37/libexec/lib/python3.11/site-packages/mackup/utils.py", line 145, in link
    os.symlink(target, link_to)
FileExistsError: [Errno 17] File exists: '/Users/matt/Library/CloudStorage/GoogleDrive-matthew.penrice@gmail.com/My Drive/syncable_apps_mackup/.config/iterm2/AppSupport/DynamicProfiles' -> '/Users/matt/.config/iterm2/AppSupport/DynamicProfiles'
```

**Comment by starsea** [comment]
what means "$XDG_CONFIG_HOME"

**Comment by jhult** [comment]
@starsea, I think you want this: `export XDG_CONFIG_HOME="$HOME/Library/Application Support"`

**Pull request merged**
