### PR TITLE
Added support for Popcorn Time

### PR DESCRIPTION
**Pull request by JacopKane**

### CODE REVIEW

**Comment by JacopKane** [comment]
I'm testing this for one week and it works just fine so far with these more minimal file configuration.
I think it is ready this time.

**Comment by lra** [comment]
Cool can u just resolve the merge conflicts?

**Comment by JacopKane** [comment]
Oh sorry didn't notice. I'll just close and make a new pull request would be cleaner i guess.

**Comment by lra** [comment]
Well, you can just add commits to this one, no need to start from scratch =)

**Pull request closed without merging**
