### PR TITLE
Add support for CopyQ and Rhythmbox

### PR DESCRIPTION
**Pull request by orschiro**

### CODE REVIEW

**Comment by orschiro** [comment]
Any chance that this pull request is getting merged any time soon to add support for CopyQ and Rhythmbox?

**Comment by vitorgalvao** [comment]
> Any chance that this pull request is getting merged any time soon to add support for CopyQ and Rhythmbox?

Tis can’t be merged because there are merge conflicts.

**Comment by orschiro** [comment]
@vitorgalvao,

Do you know what the merge conflict is? 

And how can I fix it?

Thankfully,

~Robert

**Comment by vitorgalvao** [comment]
Rebase your changes on top of master: `git pull --rebase upstream master` (`upstream` might be a different remote, depending on how you set it up) and it should tell you what the conflicts are. [More instructions](https://help.github.com/articles/resolving-a-merge-conflict-from-the-command-line/).

**Comment by orschiro** [comment]
@vitorgalvao,

I tried to rebase my branch. 

Do you think it's all good now?

**Comment by vitorgalvao** [comment]
You have an extraneous merge commit that ideally wouldn’t be there, but yes, it is mergeable now.

**Comment by orschiro** [comment]
Yeah, I'm sorry for the overhead. 

Anyway, looking forward to seeing this one merged.

Thanks for your help!

~Robert

**Comment by lra** [comment]
can you add Rhythmbox to the README?

**Comment by orschiro** [comment]
Dear @lra,

Thanks for your feedback!

I hope the commit 1e88f51 is satisfactory. 

~Robert

**Comment by lra** [comment]
all good =)

**Comment by orschiro** [comment]
Great, thank you so much! :)

~Robert

**Pull request merged**
