### PR TITLE
Add support for Mail

### PR DESCRIPTION
**Pull request by kopiro**
### All submissions

* [X] I have followed the [Contributing Guidelines](https://github.com/lra/mackup/blob/master/.github/CONTRIBUTING.md)
* [X] I have checked to ensure there aren't other open [Pull Requests](https://github.com/lra/mackup/pulls) for the same update/change

### Adding/updating Application X Support

* [X] This PR is only for one application
* [X] It has been added to the list of supported applications in the [README](https://github.com/lra/mackup/blob/master/README.md)
* [X] Changes have been added to the WIP section of the [CHANGELOG](https://github.com/lra/mackup/blob/master/CHANGELOG.md)
* [X] Syncing does not break the application
* [X] Syncing does not compete with any syncing functionality internal to the application
* [X] The configuration syncs the minimal set of data
* [X] No file specific to the local workstation is synced
* [X] No sensitive data is synced

### Improving the Mackup codebase

* [X] My submission passes the [tests](https://github.com/lra/mackup/tree/master/tests)
* [X] I have linted the code locally prior to submission
* [ ] I have written new tests as applicable
* [ ] I have added an explanation of what the changes do

### CODE REVIEW

**Review by lra — COMMENTED** [review]
Are you using this configuration? I keep adding and removing Apple apps because they usually overwrite linked config files.

**Comment by muescha** [comment]
should there be an reverse type of config files>? - where the config files are mirror'ed to the original file instead of sym linking it?

**Comment by joshmedeski** [comment]
That concept is not supported and would defeat the purpose of mackup. If Apple overwrites the config files we may not be able to add Mail to the supported mackup apps.

**Comment by kopiro** [comment]
Hello, my config file is still a symlink :)

```
flaviod:» ls -la ~/Library/Preferences/com.apple.mail.plist                   1 ↵
lrwxr-xr-x  1 flaviod  staff  73 May 10 14:59 /Users/flaviod/Library/Preferences/com.apple.mail.plist -> /Users/flaviod/.computers/mackup/Library/Preferences/com.apple.mail.plist
```

**Comment by joshmedeski** [comment]
@lra I'll let you merge this with your discretion.

@kopiro if this doesn't get merged you can always use a custom config file to sync this yourself.

**Comment by kopiro** [comment]
Yeah absolutely, what's what I'm doing :)

**Review by lra — APPROVED** [review]
We'll see, I'll just remove it at the 1st complain.

**Pull request merged**
