### PR TITLE
Add support for Amphetamine

### PR DESCRIPTION
**Pull request by mdentinho**

### CODE REVIEW

**Comment by olimorris** [comment]
@mdentinho seem to be getting a weird error with this:

https://www.dropbox.com/s/l3pbrcs6n9ifpjs/Screenshot%202017-01-24%2020.31.31.png?dl=0

**Comment by lra** [comment]
yeah it's been merged but not released yet -_-
expect a release soon

**Comment by olimorris** [comment]
I'm getting a new Mac tomorrow...any plans to do it tonight ;-)

**Comment by lra** [comment]
done: https://github.com/lra/mackup/releases/tag/0.8.16

**Pull request merged**
