### PR TITLE
Added support for Spacemacs

### PR DESCRIPTION
**Pull request by x-ji**
Spacemacs https://github.com/syl20bnr/spacemacs is an Emacs advanced Kit focused on Evil. It modifies `.emacs.d`(which is already backed up in Mackup) but also creates its own dotfile called `.spacemacs` in home folder.

### CODE REVIEW

**Comment by lra** [comment]
Can you add `.emacs.d` if it's a dependancy?

**Comment by x-ji** [comment]
@lra Sure. I thought `emacs.cfg` already specified that though. That wouldn't be an issue?

**Comment by lra** [comment]
nope it should not be

**Comment by lra** [comment]
`.emacs` too?

**Comment by lra** [comment]
mmmh maybe you are right we should not merge them and rely on the user to explicitely activate support for emacs.
Can you remove it? =)

**Comment by x-ji** [comment]
Done

**Pull request merged**
