### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by revolter**
Added instructions for testing mackup fork locally

### CODE REVIEW

**Comment by lra** [comment]
Can you fix the markdown? See `ci/circleci` status

**Comment by revolter** [comment]
I don't understand what is wrong and how to fix it.

**Comment by mbaechtold** [comment]
Could you please rebase onto the `master` branch and ideally squash the 3 commits into 1 commit?

**Comment by revolter** [comment]
Well, the squashing usually takes place at merge time from what I've seen on my past PRs. I think it's better to have the whole commits here if needed, but only one commit on merge.

**Comment by revolter** [comment]
Wow, years pass faster on GitHub than in real life! Can't believe I created this one year ago 😲

**Comment by revolter** [comment]
@lra, Care to complete the review and merge this?

**Pull request merged**
