### PR TITLE
Add Kaggle Support

### PR DESCRIPTION
**Pull request by ryoppippi**
https://github.com/Kaggle/kaggle-api

### CODE REVIEW

**Comment by ionlights** [comment]
@ryoppippi confirming that this looks good for `kaggle`. (am no reviewer, just throwing some support).

**Comment by ryoppippi** [comment]
Done! please check it!

**Comment by joshmedeski** [comment]
Please fix the conflicting changes and it looks like the URL is pointing to the Station app, not Kaggle. Please fix that as well 🙂

**Comment by ryoppippi** [comment]
Yes I fixed it!

**Pull request merged**
