### PR TITLE
Update spectacle.cfg

### PR DESCRIPTION
**Pull request by knoopx**
Also sync shortcuts

### CODE REVIEW

**Comment by MadeOfMagicAndWires** [comment]
Also, turns out this was already worked on: #982

**Comment by notcome** [comment]
@MadeOfMagicAndWires The pull request you referred to was blocked. @mbaechtold said that pull request did not update `CHANGELOG.md`, though I believe the pull request already did that. Could we simply pass the first pull request? This is just two line without any significant work required, but causing Spectacle unable to synchronize is really disturbing.

**Comment by lra** [comment]
I just merged #982.
If you think only the `Shortcuts.json` file and not the whole folder should be synced, please let us know and we'll merge this one too.

**Comment by notcome** [comment]
@lra Thanks for the merge! I think they are functionally equivalent since the only file in that directory is `Shortcuts.json`. I would say we can safely close this one, but I am not the author of this pull request, so that is just a suggestion.

**Comment by lra** [comment]
Ok let's close this then, and revisit if someone has a better option.

**Pull request closed without merging**
