### PR TITLE
fix: Deprecated SafeConfigParser resolved

### LINKED ISSUE #1948: Config Parser deprecated issue
``` ~ % mackup restore -f 
Traceback (most recent call last):
  File "/usr/local/bin/mackup", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/Cellar/mackup/0.8.37/libexec/lib/python3.12/site-packages/mackup/main.py", line 66, in main
    mckp = Mackup()
           ^^^^^^^^
  File "/usr/local/Cellar/mackup/0.8.37/libexec/lib/python3.12/site-packages/mackup/mackup.py", line 24, in __init__
    self._config = config.Config()
                   ^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/mackup/0.8.37/libexec/lib/python3.12/site-packages/mackup/config.py", line 46, in __init__
    self._parser = self._setup_parser(filename)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/mackup/0.8.37/libexec/lib/python3.12/site-packages/mackup/config.py", line 150, in _setup_parser
    parser = configparser.SafeConfigParser(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
```

### PR DESCRIPTION
**Pull request by koconder**
Fixes #1948

### All submissions

* [x] I have followed the [Contributing Guidelines](https://github.com/lra/mackup/blob/master/.github/CONTRIBUTING.md)
* [x] I have checked to ensure there aren't other open [Pull Requests](https://github.com/lra/mackup/pulls) for the same update/change

### Adding/updating Application X Support

* [ ] This PR is only for one application
* [ ] It has been added to the list of supported applications in the [README](https://github.com/lra/mackup/blob/master/README.md)
* [ ] Changes have been added to the WIP section of the [CHANGELOG](https://github.com/lra/mackup/blob/master/CHANGELOG.md)
* [ ] Syncing does not break the application
* [ ] Syncing does not compete with any syncing functionality internal to the application
* [ ] The configuration syncs the minimal set of data
* [ ] No file specific to the local workstation is synced
* [ ] No sensitive data is synced

### Improving the Mackup codebase

* [x] My submission passes the [tests](https://github.com/lra/mackup/tree/master/tests)
* [x] I have linted the code locally prior to submission
* [x] I have written new tests as applicable
* [x] I have added an explanation of what the changes do

### CODE REVIEW

**Comment by brendanfalk** [comment]
This issues seems to be apparent for a lot of ppl (see https://github.com/lra/mackup/issues/1948). This fix solves it. Would appreciate it getting it merged into main so we don't have to maintain a local fork

**Comment by magicwenli** [comment]
Confirmed.

**Comment by ChenYuHo** [comment]
@lra

**Comment by blueben** [comment]
Any timeline on merge?

**Comment by frederikkempe** [comment]
Same. Just bought myself a new Macbook. Desperately waiting for this fix to be able to restore my settings on my new device.

**Comment by lra** [comment]
Sorry all, I had to fix all the CI/release pipeline before I could push a new version, I'll try to push a new release tonight.

**Review by lra — APPROVED** [review]
Thanks!

**Pull request merged**
