### PR TITLE
Improve the error message when no storage is found

### PR DESCRIPTION
**Pull request by Crocmagnon**
This relates to issue #1621. It improves the error message when the storage is not found by pointing the user to the docs.

This is useful for first-time users as they could otherwise just understand that only Dropbox is supported.

I don't know if it closes the issue but at least it improves the situation described.

### CODE REVIEW

**Review by lra — APPROVED** [review]
Makes sense

**Comment by lra** [comment]
Can you check the CI errors?

**Comment by Crocmagnon** [comment]
Yup, I'm on it.

**Comment by Crocmagnon** [comment]
Done, I cleaned up the commits for the sake of your history.

**Pull request merged**
