### PR TITLE
Update sublime-text-3.cfg

### PR DESCRIPTION
**Pull request by babygau**
- Backup `Packages` and `Installed Packages` folders which allow user to fully restore not only configuration but also plugins

### CODE REVIEW

**Comment by lra** [comment]
What about saving the whole `Library/Application Support/Sublime Text 3` then?

**Comment by thibaultCha** [comment]
:+1: to this

**Comment by lra** [comment]
But that goes against what's being said at https://packagecontrol.io/docs/syncing

**Comment by thibaultCha** [comment]
@ira Indeed, I missed #169 which was mentioning that.

**Pull request closed without merging**
