### PR TITLE
add global git ignore

### PR DESCRIPTION
**Pull request by lorenzofanchi**

### CODE REVIEW

**Comment by lra** [comment]
This has been removed before, it's not standard: https://github.com/lra/mackup/pull/351

**Comment by lorenzofanchi** [comment]
so should `.config/git/ignore` be added?

see https://github.com/lra/mackup/pull/926#issuecomment-273964314

**Comment by lra** [comment]
it's already there:
```
[xdg_configuration_files]
git/ignore
```

`xdg_configuration_files` points to your XDG folder, `.config` by default.

**Comment by lorenzofanchi** [comment]
what about when that's not set? running mackup on my machine doesn't back it up..

**Comment by pvinis** [comment]
Well that's kind of a config problem, no? Otherwise let's also put '/Users/lorenzofanchi/.config/git/ignore'

**Comment by lorenzofanchi** [comment]
Not sure.. From the linked post (which draws from https://git-scm.com/docs/gitignore) it reads:

> If $XDG_CONFIG_HOME is either not set or empty, $HOME/.config/git/ignore is used instead.

So I would gather it would actually make sense to include `.config/git/ignore`

No need for witty remarks btw. We're all just here to improve mackup....

**Comment by lra** [comment]
if `XDG_CONFIG_HOME` is not set, Mackup act as if it was set to `~/.config`, the expected default.

> I would argue it would actually make sense to include .config/git/ignore

It's what's already defined in the config file. If it's not working, it's a bug.

**Comment by lorenzofanchi** [comment]
Tested the develop version and everything now works as expected

**Pull request closed without merging**
