### PR TITLE
Improved Readme

### PR DESCRIPTION
**Pull request by demidovakatya**
fixed typos, rearranged some sentences, etc.

### CODE REVIEW

**Comment by lra** [comment]
The tests are failing, can you check CircleCI?

**Comment by demidovakatya** [comment]
@lra 

```

**Comment by demidovakatya** [comment]
Fixed that! 

If you don't mind, I'd work more with the texts. And if I understand correctly, CircleCi checks if `.md` files follow [these](https://github.com/mivok/markdownlint/blob/master/docs/RULES.md) (or similar) rules? No question marks at the end of headers, yep?

**Comment by lra** [comment]
exactly ;)

**Comment by lra** [comment]
thanks for this ;)

**Pull request merged**
